export const data = [
  {
    topDashboard: [
      {
        id: 1,
        socialMediaIcon: require('./images/icon-facebook.svg').default,
        user: '@nathanf',
        followers: 1987,
        votesIcon: require('./images/icon-up.svg').default,
        count: 12,
        socialMediaPlatform: 'facebook',
      },
      {
        id: 2,
        socialMediaIcon: require('./images/icon-twitter.svg').default,
        user: '@nathanf',
        followers: 1044,
        votesIcon: require('./images/icon-up.svg').default,
        count: 99,
        socialMediaPlatform: 'twitter',
      },
      {
        id: 3,
        socialMediaIcon: require('./images/icon-instagram.svg').default,
        user: '@realnathanf',
        followers: '11K',
        votesIcon: require('./images/icon-up.svg').default,
        count: 1099,
        socialMediaPlatform: 'instagram',
      },
      {
        id: 4,
        socialMediaIcon: require('./images/icon-youtube.svg').default,
        user: 'Nathan F.',
        followers: 8239,
        votesIcon: require('./images/icon-down.svg').default,
        count: 144,
        socialMediaPlatform: 'youtube',
      },
    ],
  },
  {
    overview: [
      {
        id: 5,
        socialMediaIcon: require('./images/icon-facebook.svg').default,
        socialMediaPlatform: 'facebook',
        count: 87,
        votesIcon: require('./images/icon-up.svg').default,
        percentage: 3,
      },
      {
        id: 6,
        socialMediaIcon: require('./images/icon-facebook.svg').default,
        socialMediaPlatform: 'facebook',
        count: 52,
        votesIcon: require('./images/icon-down.svg').default,
        percentage: 2,
      },
      {
        id: 7,
        socialMediaIcon: require('./images/icon-instagram.svg').default,
        socialMediaPlatform: 'instagram',
        count: 5462,
        votesIcon: require('./images/icon-up.svg').default,
        percentage: 2257,
      },
      {
        id: 8,
        socialMediaIcon: require('./images/icon-instagram.svg').default,
        socialMediaPlatform: 'instagram',
        count: '52k',
        votesIcon: require('./images/icon-up.svg').default,
        percentage: 1375,
      },
      {
        id: 9,
        socialMediaIcon: require('./images/icon-twitter.svg').default,
        socialMediaPlatform: 'twitter',
        count: 117,
        votesIcon: require('./images/icon-up.svg').default,
        percentage: 303,
      },
      {
        id: 10,
        socialMediaIcon: require('./images/icon-twitter.svg').default,
        socialMediaPlatform: 'twitter',
        count: 507,
        votesIcon: require('./images/icon-up.svg').default,
        percentage: 553,
      },
      {
        id: 11,
        socialMediaIcon: require('./images/icon-youtube.svg').default,
        socialMediaPlatform: 'youtube',
        count: 107,
        votesIcon: require('./images/icon-down.svg').default,
        percentage: 19,
      },
      {
        id: 12,
        socialMediaIcon: require('./images/icon-youtube.svg').default,
        socialMediaPlatform: 'youtube',
        count: 1407,
        votesIcon: require('./images/icon-down.svg').default,
        percentage: 12,
      },
    ],
  },
]

export default data
